---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-machine
spec:
  encryptedData:
    token: AgBRFW/ffBz0CCxm2QQ5NxWHqDRKzSyQ6FeBaA+vQ2Mdpy27G02YhY4uPWtztLou8SLMt4ZTg9qbrBo2eScWXOHtssK/NiC/NCyIZvLaldulsbxtMqhEi8T0Apb3PC80PyH/jJXcLIkr+Hcie8pVShPKAtfLYyzUWb4njphQMSCW2FsUFYOG/r5eo+AZS5yXO++/ieAyHhFTVMOloG4vvR7Cbf/6pIFqg+gIPAD/TYcTvg3FHqzQBgTdtcmq4/2UZByJqfUAchyymHlVWHgveRmWEntfJ8YpJzmvp9pSRgKLqeQ/CUGhC3G34MgJDBgfZxlhx5ms3gUAMyzRzt9mevNgnkWv/e7xX4piv6FVtBEtnDCKWUp9vtWoDaT3B8iKeqJ48z/8Qn/jpptiz1mu3ZgKeBcR9Z1Aj27uxvdS3eyLhEgyvkXkpgxMamNfX3AGhNL5k9DkCYgrhdDq5xTsZNUx148etwwNPibiyBITUx3/KBj/lmrIZl+clpRtMa67ftsiJc+DHDq5djsjmwTZTTu0OxhOEC0eA1XFH21iXg5IbCkeDVe9zyewISrGV7C+5TQhhXl28QCb7Y+6fmxmbado3U8iMQW9Z/a7Ql6kxYZx7FGk/1kwHcDGrIW/X4Jsc/3H/je6YvbvnoqrF7gax+SwuuOCn6Dyi0/Co+N4dr5HzVRIV1c+uHTw1BhWpHqJJgaswn50PvmHS6xt54J0r07s6lnowgR1cYKk2fETu4BXqPxyVdaMJxJa
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-machine
