apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: resolve-props
spec:
  params:
    - name: ir-source-directory
  results:
    - name: ir-project
    - name: ir-application-name
    - name: ir-release-name
    - name: ir-configuration-keystore
    - name: ir-configuration-truststore
    - name: ir-configuration-setdbparms
    - name: ir-configuration-runtimeconf
    - name: ir-configuration-policyproject
    - name: ir-configuration-loopbackdatasource
    - name: mq-queue-name
    - name: mq-end-point-policy-file
    - name: registry-host
    - name: previous-ir-genenration
    - name: previous-deployment-revision
    - name: endpoint-path
    - name: ir-configurations
    - name: ir-license
    - name: ir-license-use
    - name: ir-service-endpoint-type
    - name: ir-version
    - name: ir-base-image
  steps:
    - name: parse-source-properties
      image: mikefarah/yq:4.7.1
      script: |
        set -ex

        properties_yaml_path=$(workspaces.input.path)/$(params.ir-source-directory)/pipeline_properties.yaml

        if [[ ! -e $properties_yaml_path ]]; then
          echo "no pipeline property file found"
          exit 0
        fi

        resolve_props() {
          exp=$1
          result_path=$2

          echo -n `yq e "$exp // [] | join (\" \")" $properties_yaml_path` > $result_path
        }

        resolve_prop() {
          exp=$1
          result_path=$2

          echo -n `yq e "$exp // \"\" " $properties_yaml_path` > $result_path
        }

        resolve_props '.integrationRuntime.project' $(results.ir-project.path)
        resolve_prop '.integrationRuntime.applicationName' $(results.ir-application-name.path)
        resolve_prop '.integrationRuntime.releaseName' $(results.ir-release-name.path)
        resolve_prop '.integrationRuntime.endpoint-path' $(results.endpoint-path.path)
        resolve_props '.integrationRuntime.configurations.keystore' $(results.ir-configuration-keystore.path)
        resolve_props '.integrationRuntime.configurations.truststore' $(results.ir-configuration-truststore.path)
        resolve_props '.integrationRuntime.configurations.setdbparms' $(results.ir-configuration-setdbparms.path)
        resolve_props '.integrationRuntime.configurations.runtimeconf' $(results.ir-configuration-runtimeconf.path)
        resolve_props '.integrationRuntime.configurations.policyproject' $(results.ir-configuration-policyproject.path)
        resolve_props '.integrationRuntime.configurations.loopbackdatasource' $(results.ir-configuration-loopbackdatasource.path)

        resolve_prop '.mq.queueName' $(results.mq-queue-name.path)
        resolve_prop '.mq.endPointPolicyFile' $(results.mq-end-point-policy-file.path)

        resolve_props '.integrationRuntime.configurations.*' $(results.ir-configurations.path)

        resolve_prop '.integrationRuntime.license.license' $(results.ir-license.path)
        resolve_prop '.integrationRuntime.license.use' $(results.ir-license-use.path)
        resolve_prop '.integrationRuntime.service.endpointType' $(results.ir-service-endpoint-type.path)
        resolve_prop '.integrationRuntime.version' $(results.ir-version.path)
        resolve_prop '.integrationRuntime.baseImage' $(results.ir-base-image.path)

    - name: resolve-ocp-properties
      image: quay.io/openshift/origin-cli:latest
      script: |
        
        release_name=$(cat $(results.ir-release-name.path))
        echo $release_name

        set +e
        previous_ir_genenration=$(oc get integrationruntime \
                $release_name -o jsonpath='{.metadata.generation}' 2>/dev/null)
        set +e

        echo -n $previous_ir_genenration > $(results.previous-ir-genenration.path)

        if [[ ! -z $previous_ir_genenration ]]; then
          oc get deployment \
                -l app.kubernetes.io/instance=$release_name \
                -o jsonpath='{$.items[0].metadata.annotations.deployment\.kubernetes\.io/revision}' 2>/dev/null > $(results.previous-deployment-revision.path)
        else
          touch $(results.previous-deployment-revision.path)
        fi

        echo -n $(oc registry info) > $(results.registry-host.path)

  workspaces:
    - name: input
