apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-promote-dev-stage
spec:
  params:
  - default: https://github.com/cloud-native-toolkit-demos/ace-customer-details.git
    name: ir-source-repo-url
    type: string
  - default: ir-source
    name: ir-source-directory
    type: string
  - default: '""'
    name: ir-source-repo-private-key
    type: string

  - default: ibm-client-key-certs
    name: key-certs-secret-name
    type: string
  - default: ibm-client.key
    name: client-key
    type: string
  - default: ibm-client.crt
    name: client-cert
    type: string
  - default: ibm-ca.crt
    name: ca-cert
    type: string
  - description: Points to the dev/staging env
    name: source-env
    type: string
    default: dev
  - description: Points to the staging/prod env
    name: destination-env
    type: string
    default: staging


  tasks:

  - name: clone-ir-source
    params:
    - name: url
      value: $(params.ir-source-repo-url)
    - name: subdirectory
      value: $(params.ir-source-directory)
    - name: deleteExisting
      value: "true"
    - name: sshPrivateKey
      value: $(params.ir-source-repo-private-key)
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace

  - name: resolve-props
    params:
    - name: ir-source-directory
      value: $(params.ir-source-directory)
    runAfter:
    - clone-ir-source
    taskRef:
      kind: Task
      name: resolve-props
    workspaces:
    - name: input
      workspace: shared-workspace

  - name: functional-test
    params:
    - name: source-env
      value: $(params.source-env)
    - name: ir-source-directory
      value: $(params.ir-source-directory)
    - name: release-name
      value: create-customer-details-rest
    - name: endpoint-path
      value: v1/createcustomer
    - name: key-certs-secret-name
      value: $(params.key-certs-secret-name)
    - name: client-key
      value: $(params.client-key)
    - name: client-cert
      value: $(params.client-cert)
    - name: ca-cert
      value: $(params.ca-cert)
    runAfter:
    - resolve-props
    taskRef:
      kind: Task
      name: functional-test
    workspaces:
    - name: workspace
      workspace: shared-workspace


  - name: gitops-for-ace
    params:
    - name: source-env
      value: $(params.source-env)
    - name: destination-env
      value: $(params.destination-env)
    - name: git-pr
      value: "true"
    runAfter:
    - functional-test
    taskRef:
      kind: Task
      name: ibm-gitops-for-ace
  workspaces:
  - name: shared-workspace
