apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-config
spec:
  params:
    - name: ir-config-repo-url
      type: string
      description: "SSH url of Configuration repository, ex: git@github.com:ace-prod-ref/ace-config.git"

    - name: ir-infra-repo-url
      type: string
      description: "SSH url of Infrastructure repository, ex: git@github.com:ace-prod-ref/ace-infra.git"

    - name: git-ops-repo-url
      type: string
      description: "SSH url of GitOps repository, ex: git@github.com:ace-prod-ref/multi-tenancy-gitops-apps.git"

    - name: gitops-apps-repo-full-name
      type: string
      description: "Repo name of GitOps repository, in github.com, ex: ace-prod-ref/multi-tenancy-gitops-apps"

    - name: github-pr-title
      type: string
      default: "Changes by Pipeline run: $(context.pipelineRun.name)"
      description: "Title of pull request"
    - name: github-pr-body
      type: string
      default: "Changes by Pipeline run: $(context.pipelineRun.name)"
      description: "Body of pull request"
    - name: github-pr-token-secret-name
      type: string
      default: cicd-acme
      description: "Personal access token for CICD bot user"

  workspaces:
    - name: shared-workspace
    - name: ace-config-repo-secret
    - name: ace-infra-repo-secret
    - name: gitops-repo-secret

  tasks:
    - name: clone-ir-config-repo
      params:
        - name: url
          value: $(params.ir-config-repo-url)
        - name: subdirectory
          value: ir-config
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
        apiVersion: tekton.dev/v1beta1
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ace-config-repo-secret

    - name: clone-ir-infra-repo
      params:
        - name: url
          value: $(params.ir-infra-repo-url)
        - name: subdirectory
          value: ir-infra
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
        apiVersion: tekton.dev/v1beta1
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ace-infra-repo-secret

    - name: clone-gitops-repo
      params:
        - name: url
          value: $(params.git-ops-repo-url)
        - name: subdirectory
          value: gitops-repo
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
        apiVersion: tekton.dev/v1beta1
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: gitops-repo-secret

    - name: resolve-props
      params:
        - name: ir-source-directory
          value: ir-config
      runAfter:
        - clone-ir-config-repo
      taskRef:
        kind: Task
        name: resolve-props
        apiVersion: tekton.dev/v1beta1
      workspaces:
        - name: input
          workspace: shared-workspace

    - name: create-config
      params:
        - name: ir-config-directory
          value: ir-config
        - name: ir-infra-directory
          value: ir-infra
        - name: ir-configuration-keystore
          value: $(tasks.resolve-props.results.ir-configuration-keystore)
        - name: ir-configuration-truststore
          value: $(tasks.resolve-props.results.ir-configuration-truststore)
        - name: ir-configuration-setdbparms
          value: $(tasks.resolve-props.results.ir-configuration-setdbparms)
        - name: ir-configuration-runtimeconf
          value: $(tasks.resolve-props.results.ir-configuration-runtimeconf)
        - name: ir-configuration-policyproject
          value: $(tasks.resolve-props.results.ir-configuration-policyproject)
        - name: ir-configuration-loopbackdatasource
          value: $(tasks.resolve-props.results.ir-configuration-loopbackdatasource)
        - name: rendered-config-directory
          value: gitops-repo/ace/environments/base/configurations
        - name: repo-directory
          value: gitops-repo
        - name: user-name
          value: "cicd.acme"
        - name: user-email
          value: "cicd@acme.com"
        - name: kustomization-path
          value: gitops-repo/ace/environments/base/kustomization.yaml
        - name: branch_name
          value: $(context.pipeline.name)-$(context.pipelineRun.name)
      runAfter:
        - resolve-props
        - clone-ir-infra-repo
        - clone-gitops-repo
      taskRef:
        kind: Task
        name: create-config
        apiVersion: tekton.dev/v1beta1
      workspaces:
        - name: workspace
          workspace: shared-workspace
        - name: ssh-directory
          workspace: gitops-repo-secret
    - name: create-pull-request
      taskRef:
        kind: Task
        name: github-open-pr
        apiVersion: tekton.dev/v1beta1
      runAfter:
        - create-config
      params:
        - name: GITHUB_HOST_URL
          value: api.github.com
        - name: REPO_FULL_NAME
          value: $(params.gitops-apps-repo-full-name)
        - name: HEAD
          value: $(context.pipeline.name)-$(context.pipelineRun.name)
        - name: BASE
          value: master
        - name: TITLE
          value: $(params.github-pr-title)
        - name: BODY
          value: $(params.github-pr-body)
        - name: GITHUB_TOKEN_SECRET_NAME
          value: $(params.github-pr-token-secret-name)

